apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w3813b8hz-go
  janus-idp.io/tekton: w3813b8hz-go
  backstage.io/kubernetes-id: w3813b8hz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w3813b8hz-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
